
project_id = "9b815f39-57d1-4d46-a461-125f65f85b8c"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_requires_email = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[edge_functions]
enabled = true
port = 54323

[functions.plaid-link-token]
verify_jwt = true

[functions.plaid-exchange-token]
verify_jwt = true

[functions.plaid-sync-accounts]
verify_jwt = true

[functions.plaid-get-accounts]
verify_jwt = true

[studio]
enabled = true
port = 54323

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
